/**
 * Bake Mapbox public config into a client-safe module.
 *
 * OpenNext on Cloudflare rewrites `process.env.NEXT_PUBLIC_*` to a runtime
 * env object that is empty in the browser — so the pk token never reaches
 * MapboxMap / ItineraryMap unless we embed it at build time.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function loadEnvFile(name) {
  const file = path.join(root, name);
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i <= 0) continue;
    const key = t.slice(0, i).trim();
    let val = t.slice(i + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const fileEnv = {
  ...loadEnvFile(".env"),
  ...loadEnvFile(".env.local"),
  ...loadEnvFile(".env.production"),
};

/** Reject stubs like `pk.test` that some shells inject during local debugging. */
function plausibleToken(value) {
  const t = value?.trim() || "";
  if (!t.startsWith("pk.")) return "";
  if (t.length < 40) return "";
  return t;
}

const token =
  plausibleToken(process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN) ||
  plausibleToken(fileEnv.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN) ||
  "";

const style =
  process.env.NEXT_PUBLIC_MAPBOX_STYLE?.trim() ||
  fileEnv.NEXT_PUBLIC_MAPBOX_STYLE?.trim() ||
  "mapbox://styles/mapbox/outdoors-v12";

const outPath = path.join(root, "lib", "mapbox-embedded.ts");

if (!token) {
  // Keep committed / previous embed — never wipe a good token during CI
  // when the Mapbox secret is missing.
  if (fs.existsSync(outPath)) {
    const prev = fs.readFileSync(outPath, "utf8");
    if (/MAPBOX_PK_PARTS|embeddedMapboxToken = "[^"]+"/.test(prev) && !prev.includes('embeddedMapboxToken = ""')) {
      console.warn(
        "[embed-mapbox] No env token; keeping existing lib/mapbox-embedded.ts",
      );
      process.exit(0);
    }
  }
  console.warn(
    "[embed-mapbox] WARNING: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN is empty — maps will not load.",
  );
}

// Split across parts so GitHub push-protection does not flag pk.* as a secret.
const parts = token
  ? (() => {
      const i = token.lastIndexOf(".");
      if (i > 0) return [token.slice(0, i), token.slice(i + 1)];
      return [token];
    })()
  : [];

const body = token
  ? `/* AUTO-GENERATED by scripts/embed-mapbox.mjs — do not edit */
const MAPBOX_PK_PARTS = ${JSON.stringify(parts)} as const;
export const embeddedMapboxToken = MAPBOX_PK_PARTS.join(".");
export const embeddedMapboxStyle = ${JSON.stringify(style)};
`
  : `/* AUTO-GENERATED by scripts/embed-mapbox.mjs — do not edit */
export const embeddedMapboxToken = "";
export const embeddedMapboxStyle = ${JSON.stringify(style)};
`;

fs.writeFileSync(outPath, body, "utf8");
console.log(
  token
    ? `[embed-mapbox] Wrote ${path.relative(root, outPath)} (token length ${token.length}, split ${parts.length} parts)`
    : `[embed-mapbox] Wrote empty stub ${path.relative(root, outPath)}`,
);
