/**
 * Bake Mapbox public config into a client-safe module.
 *
 * OpenNext on Cloudflare rewrites `process.env.NEXT_PUBLIC_*` to a runtime
 * env object that is empty in the browser — so the pk token never reaches
 * MapboxMap / ItineraryMap unless we embed it at build time.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function loadEnvFile(name) {
  const file = path.join(root, name);
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i <= 0) continue;
    const key = t.slice(0, i).trim();
    let val = t.slice(i + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const fileEnv = {
  ...loadEnvFile(".env"),
  ...loadEnvFile(".env.local"),
  ...loadEnvFile(".env.production"),
};

/** Reject stubs like `pk.test` that some shells inject during local debugging. */
function plausibleToken(value) {
  const t = value?.trim() || "";
  if (!t.startsWith("pk.")) return "";
  if (t.length < 40) return "";
  return t;
}

const token =
  plausibleToken(process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN) ||
  plausibleToken(fileEnv.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN) ||
  "";

const style =
  process.env.NEXT_PUBLIC_MAPBOX_STYLE?.trim() ||
  fileEnv.NEXT_PUBLIC_MAPBOX_STYLE?.trim() ||
  "mapbox://styles/mapbox/outdoors-v12";

const outPath = path.join(root, "lib", "mapbox-embedded.ts");
const body = `/* AUTO-GENERATED by scripts/embed-mapbox.mjs — do not edit */
export const embeddedMapboxToken = ${JSON.stringify(token)};
export const embeddedMapboxStyle = ${JSON.stringify(style)};
`;

fs.writeFileSync(outPath, body, "utf8");

if (!token) {
  console.warn(
    "[embed-mapbox] WARNING: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN is empty — maps will not load in production.",
  );
} else {
  console.log(
    `[embed-mapbox] Wrote ${path.relative(root, outPath)} (token length ${token.length})`,
  );
}
