/* AUTO-GENERATED by scripts/embed-mapbox.mjs — do not edit */
const MAPBOX_PK_PARTS = ["pk.eyJ1IjoiY2hlZXNlY3JlYW0iLCJhIjoiY21zNDFwbzN6MXphZTNhcTA2d2k2ZzhjeCJ9","RBWabfHmhTK7hyd5yPxxHA"] as const;
export const embeddedMapboxToken = MAPBOX_PK_PARTS.join(".");
export const embeddedMapboxStyle = "mapbox://styles/mapbox/outdoors-v12";
