/* AUTO-GENERATED by scripts/embed-mapbox.mjs — do not edit.
 * Populated at build/dev from NEXT_PUBLIC_MAPBOX_* or .env* files.
 * Keep this committed stub empty so git push protection stays happy. */
export const embeddedMapboxToken = "";
export const embeddedMapboxStyle = "mapbox://styles/mapbox/outdoors-v12";
